# author: Mark Westerweel / Mwest2020

exclude_words:
  - Documentation Build Failed

repositories:
  - owner: ConductionNL
    repo: woo-website-template
  - owner: ConductionNL
    repo: openregister
  - owner: ConductionNL
    repo: zaakafhandelapp
  - owner: ConductionNL
    repo: opencatalogi
  - owner: ConductionNL
    repo: larpingapp
  - owner: ConductionNL
    repo: openconnector
  - owner: ConductionNL
    repo: softwarecatalog
  
  - owner: OpenCatalogi
    repo: .github
  - owner: OpenCatalogi
    repo: publiccode-action
  - owner: OpenCatalogi
    repo: product-website
  - owner: OpenCatalogi
    repo: OpenCatalogiBundle
  - owner: OpenCatalogi
    repo: opencatalogi.nl
  - owner: OpenCatalogi
    repo: opencatalogi-action
  - owner: OpenCatalogi
    repo: leiden
  - owner: OpenCatalogi
    repo: opencatalogi
  - owner: VNG-Realisatie
    repo: softwarecatalogus
  
  - owner: Geleiding
    repo: .github
  # ... add more repositories as needed
